made sure onLoad's not overriden/used, added graceful disable on thrown exceptions to prevent some noclassdeffounderror worked more on config the code as it is now, it's non-usable, still work in progress (due to the config being reworked)